use enigo::Key as EnigoKey;
use rdev::Key as RdevKey;

pub fn js_code_to_rdev(code: &str) -> Option<RdevKey> {
    Some(match code {
        // Letters
        "KeyA" => RdevKey::KeyA,
        "KeyB" => RdevKey::KeyB,
        "KeyC" => RdevKey::KeyC,
        "KeyD" => RdevKey::KeyD,
        "KeyE" => RdevKey::KeyE,
        "KeyF" => RdevKey::KeyF,
        "KeyG" => RdevKey::KeyG,
        "KeyH" => RdevKey::KeyH,
        "KeyI" => RdevKey::KeyI,
        "KeyJ" => RdevKey::KeyJ,
        "KeyK" => RdevKey::KeyK,
        "KeyL" => RdevKey::KeyL,
        "KeyM" => RdevKey::KeyM,
        "KeyN" => RdevKey::KeyN,
        "KeyO" => RdevKey::KeyO,
        "KeyP" => RdevKey::KeyP,
        "KeyQ" => RdevKey::KeyQ,
        "KeyR" => RdevKey::KeyR,
        "KeyS" => RdevKey::KeyS,
        "KeyT" => RdevKey::KeyT,
        "KeyU" => RdevKey::KeyU,
        "KeyV" => RdevKey::KeyV,
        "KeyW" => RdevKey::KeyW,
        "KeyX" => RdevKey::KeyX,
        "KeyY" => RdevKey::KeyY,
        "KeyZ" => RdevKey::KeyZ,

        // Number row
        "Digit0" => RdevKey::Num0,
        "Digit1" => RdevKey::Num1,
        "Digit2" => RdevKey::Num2,
        "Digit3" => RdevKey::Num3,
        "Digit4" => RdevKey::Num4,
        "Digit5" => RdevKey::Num5,
        "Digit6" => RdevKey::Num6,
        "Digit7" => RdevKey::Num7,
        "Digit8" => RdevKey::Num8,
        "Digit9" => RdevKey::Num9,

        // Numpad
        "Numpad0" => RdevKey::Kp0,
        "Numpad1" => RdevKey::Kp1,
        "Numpad2" => RdevKey::Kp2,
        "Numpad3" => RdevKey::Kp3,
        "Numpad4" => RdevKey::Kp4,
        "Numpad5" => RdevKey::Kp5,
        "Numpad6" => RdevKey::Kp6,
        "Numpad7" => RdevKey::Kp7,
        "Numpad8" => RdevKey::Kp8,
        "Numpad9" => RdevKey::Kp9,
        "NumpadDecimal" => RdevKey::KpDelete,
        "NumpadEnter" => RdevKey::KpReturn,
        "NumpadAdd" => RdevKey::KpPlus,
        "NumpadSubtract" => RdevKey::KpMinus,
        "NumpadMultiply" => RdevKey::KpMultiply,
        "NumpadDivide" => RdevKey::KpDivide,

        // Modifiers
        "AltLeft" | "AltRight" => RdevKey::Alt,
        "ControlLeft" => RdevKey::ControlLeft,
        "ControlRight" => RdevKey::ControlRight,
        "ShiftLeft" => RdevKey::ShiftLeft,
        "ShiftRight" => RdevKey::ShiftRight,
        "MetaLeft" => RdevKey::MetaLeft,
        "MetaRight" => RdevKey::MetaRight,
        "CapsLock" => RdevKey::CapsLock,
        "NumLock" => RdevKey::NumLock,

        // Navigation
        "ArrowUp" => RdevKey::UpArrow,
        "ArrowDown" => RdevKey::DownArrow,
        "ArrowLeft" => RdevKey::LeftArrow,
        "ArrowRight" => RdevKey::RightArrow,
        "Home" => RdevKey::Home,
        "End" => RdevKey::End,
        "PageUp" => RdevKey::PageUp,
        "PageDown" => RdevKey::PageDown,
        "Insert" => RdevKey::Insert,
        "Delete" => RdevKey::Delete,

        // Control keys
        "Enter" => RdevKey::Return,
        "Escape" => RdevKey::Escape,
        "Backspace" => RdevKey::Backspace,
        "Tab" => RdevKey::Tab,
        "Space" => RdevKey::Space,
        "PrintScreen" => RdevKey::PrintScreen,
        "ScrollLock" => RdevKey::ScrollLock,
        "Pause" => RdevKey::Pause,

        // Punctuation / symbols by physical key
        "Backquote" => RdevKey::BackQuote,
        "Minus" => RdevKey::Minus,
        "Equal" => RdevKey::Equal,
        "BracketLeft" => RdevKey::LeftBracket,
        "BracketRight" => RdevKey::RightBracket,
        "Backslash" => RdevKey::BackSlash,
        "IntlBackslash" => RdevKey::IntlBackslash,
        "Semicolon" => RdevKey::SemiColon,
        "Quote" => RdevKey::Quote,
        "Comma" => RdevKey::Comma,
        "Period" => RdevKey::Dot,
        "Slash" => RdevKey::Slash,

        // Function keys
        "F1" => RdevKey::F1,
        "F2" => RdevKey::F2,
        "F3" => RdevKey::F3,
        "F4" => RdevKey::F4,
        "F5" => RdevKey::F5,
        "F6" => RdevKey::F6,
        "F7" => RdevKey::F7,
        "F8" => RdevKey::F8,
        "F9" => RdevKey::F9,
        "F10" => RdevKey::F10,
        "F11" => RdevKey::F11,
        "F12" => RdevKey::F12,

        _ => return None,
    })
}

pub fn rdev_to_js_code(key: RdevKey) -> Option<&'static str> {
    Some(match key {
        // Letters
        RdevKey::KeyA => "KeyA",
        RdevKey::KeyB => "KeyB",
        RdevKey::KeyC => "KeyC",
        RdevKey::KeyD => "KeyD",
        RdevKey::KeyE => "KeyE",
        RdevKey::KeyF => "KeyF",
        RdevKey::KeyG => "KeyG",
        RdevKey::KeyH => "KeyH",
        RdevKey::KeyI => "KeyI",
        RdevKey::KeyJ => "KeyJ",
        RdevKey::KeyK => "KeyK",
        RdevKey::KeyL => "KeyL",
        RdevKey::KeyM => "KeyM",
        RdevKey::KeyN => "KeyN",
        RdevKey::KeyO => "KeyO",
        RdevKey::KeyP => "KeyP",
        RdevKey::KeyQ => "KeyQ",
        RdevKey::KeyR => "KeyR",
        RdevKey::KeyS => "KeyS",
        RdevKey::KeyT => "KeyT",
        RdevKey::KeyU => "KeyU",
        RdevKey::KeyV => "KeyV",
        RdevKey::KeyW => "KeyW",
        RdevKey::KeyX => "KeyX",
        RdevKey::KeyY => "KeyY",
        RdevKey::KeyZ => "KeyZ",

        // Number row
        RdevKey::Num0 => "Digit0",
        RdevKey::Num1 => "Digit1",
        RdevKey::Num2 => "Digit2",
        RdevKey::Num3 => "Digit3",
        RdevKey::Num4 => "Digit4",
        RdevKey::Num5 => "Digit5",
        RdevKey::Num6 => "Digit6",
        RdevKey::Num7 => "Digit7",
        RdevKey::Num8 => "Digit8",
        RdevKey::Num9 => "Digit9",

        // Numpad
        RdevKey::Kp0 => "Numpad0",
        RdevKey::Kp1 => "Numpad1",
        RdevKey::Kp2 => "Numpad2",
        RdevKey::Kp3 => "Numpad3",
        RdevKey::Kp4 => "Numpad4",
        RdevKey::Kp5 => "Numpad5",
        RdevKey::Kp6 => "Numpad6",
        RdevKey::Kp7 => "Numpad7",
        RdevKey::Kp8 => "Numpad8",
        RdevKey::Kp9 => "Numpad9",
        RdevKey::KpDelete => "NumpadDecimal",
        RdevKey::KpReturn => "NumpadEnter",
        RdevKey::KpPlus => "NumpadAdd",
        RdevKey::KpMinus => "NumpadSubtract",
        RdevKey::KpMultiply => "NumpadMultiply",
        RdevKey::KpDivide => "NumpadDivide",

        // Modifiers
        RdevKey::Alt => "AltLeft", // Note: JS has AltLeft/AltRight, rdev has single Alt
        RdevKey::ControlLeft => "ControlLeft",
        RdevKey::ControlRight => "ControlRight",
        RdevKey::ShiftLeft => "ShiftLeft",
        RdevKey::ShiftRight => "ShiftRight",
        RdevKey::MetaLeft => "MetaLeft",
        RdevKey::MetaRight => "MetaRight",
        RdevKey::CapsLock => "CapsLock",
        RdevKey::NumLock => "NumLock",

        // Navigation
        RdevKey::UpArrow => "ArrowUp",
        RdevKey::DownArrow => "ArrowDown",
        RdevKey::LeftArrow => "ArrowLeft",
        RdevKey::RightArrow => "ArrowRight",
        RdevKey::Home => "Home",
        RdevKey::End => "End",
        RdevKey::PageUp => "PageUp",
        RdevKey::PageDown => "PageDown",
        RdevKey::Insert => "Insert",
        RdevKey::Delete => "Delete",

        // Control keys
        RdevKey::Return => "Enter",
        RdevKey::Escape => "Escape",
        RdevKey::Backspace => "Backspace",
        RdevKey::Tab => "Tab",
        RdevKey::Space => "Space",
        RdevKey::PrintScreen => "PrintScreen",
        RdevKey::ScrollLock => "ScrollLock",
        RdevKey::Pause => "Pause",

        // Punctuation / symbols
        RdevKey::BackQuote => "Backquote",
        RdevKey::Minus => "Minus",
        RdevKey::Equal => "Equal",
        RdevKey::LeftBracket => "BracketLeft",
        RdevKey::RightBracket => "BracketRight",
        RdevKey::BackSlash => "Backslash",
        RdevKey::IntlBackslash => "IntlBackslash",
        RdevKey::SemiColon => "Semicolon",
        RdevKey::Quote => "Quote",
        RdevKey::Comma => "Comma",
        RdevKey::Dot => "Period",
        RdevKey::Slash => "Slash",

        // Function keys
        RdevKey::F1 => "F1",
        RdevKey::F2 => "F2",
        RdevKey::F3 => "F3",
        RdevKey::F4 => "F4",
        RdevKey::F5 => "F5",
        RdevKey::F6 => "F6",
        RdevKey::F7 => "F7",
        RdevKey::F8 => "F8",
        RdevKey::F9 => "F9",
        RdevKey::F10 => "F10",
        RdevKey::F11 => "F11",
        RdevKey::F12 => "F12",

        // Unsupported keys
        _ => return None,
    })
}

pub fn rdev_to_enigo_key(key: RdevKey) -> Option<EnigoKey> {
    Some(match key {
        // Letters
        RdevKey::KeyA => EnigoKey::A,
        RdevKey::KeyB => EnigoKey::B,
        RdevKey::KeyC => EnigoKey::C,
        RdevKey::KeyD => EnigoKey::D,
        RdevKey::KeyE => EnigoKey::E,
        RdevKey::KeyF => EnigoKey::F,
        RdevKey::KeyG => EnigoKey::G,
        RdevKey::KeyH => EnigoKey::H,
        RdevKey::KeyI => EnigoKey::I,
        RdevKey::KeyJ => EnigoKey::J,
        RdevKey::KeyK => EnigoKey::K,
        RdevKey::KeyL => EnigoKey::L,
        RdevKey::KeyM => EnigoKey::M,
        RdevKey::KeyN => EnigoKey::N,
        RdevKey::KeyO => EnigoKey::O,
        RdevKey::KeyP => EnigoKey::P,
        RdevKey::KeyQ => EnigoKey::Q,
        RdevKey::KeyR => EnigoKey::R,
        RdevKey::KeyS => EnigoKey::S,
        RdevKey::KeyT => EnigoKey::T,
        RdevKey::KeyU => EnigoKey::U,
        RdevKey::KeyV => EnigoKey::V,
        RdevKey::KeyW => EnigoKey::W,
        RdevKey::KeyX => EnigoKey::X,
        RdevKey::KeyY => EnigoKey::Y,
        RdevKey::KeyZ => EnigoKey::Z,

        // Number row
        RdevKey::Num0 => EnigoKey::Num0,
        RdevKey::Num1 => EnigoKey::Num1,
        RdevKey::Num2 => EnigoKey::Num2,
        RdevKey::Num3 => EnigoKey::Num3,
        RdevKey::Num4 => EnigoKey::Num4,
        RdevKey::Num5 => EnigoKey::Num5,
        RdevKey::Num6 => EnigoKey::Num6,
        RdevKey::Num7 => EnigoKey::Num7,
        RdevKey::Num8 => EnigoKey::Num8,
        RdevKey::Num9 => EnigoKey::Num9,

        // Numpad
        RdevKey::Kp0 => EnigoKey::Numpad0,
        RdevKey::Kp1 => EnigoKey::Numpad1,
        RdevKey::Kp2 => EnigoKey::Numpad2,
        RdevKey::Kp3 => EnigoKey::Numpad3,
        RdevKey::Kp4 => EnigoKey::Numpad4,
        RdevKey::Kp5 => EnigoKey::Numpad5,
        RdevKey::Kp6 => EnigoKey::Numpad6,
        RdevKey::Kp7 => EnigoKey::Numpad7,
        RdevKey::Kp8 => EnigoKey::Numpad8,
        RdevKey::Kp9 => EnigoKey::Numpad9,
        RdevKey::KpDelete => EnigoKey::Decimal,
        RdevKey::KpReturn => EnigoKey::Return,
        RdevKey::KpPlus => EnigoKey::Add,
        RdevKey::KpMinus => EnigoKey::Subtract,
        RdevKey::KpMultiply => EnigoKey::Multiply,
        RdevKey::KpDivide => EnigoKey::Divide,

        // Modifiers
        RdevKey::Alt => EnigoKey::Alt,
        RdevKey::ControlLeft => EnigoKey::Control,
        RdevKey::ControlRight => EnigoKey::Control,
        RdevKey::ShiftLeft => EnigoKey::Shift,
        RdevKey::ShiftRight => EnigoKey::Shift,
        RdevKey::MetaLeft => EnigoKey::Meta,
        RdevKey::MetaRight => EnigoKey::Meta,
        RdevKey::CapsLock => EnigoKey::CapsLock,
        RdevKey::NumLock => EnigoKey::Numlock,

        // Navigation
        RdevKey::UpArrow => EnigoKey::UpArrow,
        RdevKey::DownArrow => EnigoKey::DownArrow,
        RdevKey::LeftArrow => EnigoKey::LeftArrow,
        RdevKey::RightArrow => EnigoKey::RightArrow,
        RdevKey::Home => EnigoKey::Home,
        RdevKey::End => EnigoKey::End,
        RdevKey::PageUp => EnigoKey::PageUp,
        RdevKey::PageDown => EnigoKey::PageDown,
        RdevKey::Insert => EnigoKey::Insert,
        RdevKey::Delete => EnigoKey::Delete,

        // Control keys
        RdevKey::Return => EnigoKey::Return,
        RdevKey::Escape => EnigoKey::Escape,
        RdevKey::Backspace => EnigoKey::Backspace,
        RdevKey::Tab => EnigoKey::Tab,
        RdevKey::Space => EnigoKey::Space,
        RdevKey::PrintScreen => EnigoKey::PrintScr,
        RdevKey::ScrollLock => return None,
        RdevKey::Pause => EnigoKey::Pause,

        // Punctuation / symbols
        RdevKey::BackQuote     => EnigoKey::Unicode('`'),
        RdevKey::Minus         => EnigoKey::Unicode('-'),
        RdevKey::Equal         => EnigoKey::Unicode('='),
        RdevKey::LeftBracket   => EnigoKey::Unicode('['),
        RdevKey::RightBracket  => EnigoKey::Unicode(']'),
        RdevKey::BackSlash     => EnigoKey::Unicode('\\'),
        RdevKey::IntlBackslash => EnigoKey::Unicode('\\'), // best approximation
        RdevKey::SemiColon     => EnigoKey::Unicode(';'),
        RdevKey::Quote         => EnigoKey::Unicode('\''),
        RdevKey::Comma         => EnigoKey::Unicode(','),
        RdevKey::Dot           => EnigoKey::Unicode('.'),
        RdevKey::Slash         => EnigoKey::Unicode('/'),

        // Function keys
        RdevKey::F1 => EnigoKey::F1,
        RdevKey::F2 => EnigoKey::F2,
        RdevKey::F3 => EnigoKey::F3,
        RdevKey::F4 => EnigoKey::F4,
        RdevKey::F5 => EnigoKey::F5,
        RdevKey::F6 => EnigoKey::F6,
        RdevKey::F7 => EnigoKey::F7,
        RdevKey::F8 => EnigoKey::F8,
        RdevKey::F9 => EnigoKey::F9,
        RdevKey::F10 => EnigoKey::F10,
        RdevKey::F11 => EnigoKey::F11,
        RdevKey::F12 => EnigoKey::F12,

        // Unsupported keys
        _ => return None,
    })
}