use rdev::Key;

use enigo::Key as EnigoKey;
use rdev::Key as RdevKey;

pub fn js_code_to_rdev(code: &str) -> Option<Key> {
    Some(match code {
        // Letters
        "KeyA" => Key::KeyA,
        "KeyB" => Key::KeyB,
        "KeyC" => Key::KeyC,
        "KeyD" => Key::KeyD,
        "KeyE" => Key::KeyE,
        "KeyF" => Key::KeyF,
        "KeyG" => Key::KeyG,
        "KeyH" => Key::KeyH,
        "KeyI" => Key::KeyI,
        "KeyJ" => Key::KeyJ,
        "KeyK" => Key::KeyK,
        "KeyL" => Key::KeyL,
        "KeyM" => Key::KeyM,
        "KeyN" => Key::KeyN,
        "KeyO" => Key::KeyO,
        "KeyP" => Key::KeyP,
        "KeyQ" => Key::KeyQ,
        "KeyR" => Key::KeyR,
        "KeyS" => Key::KeyS,
        "KeyT" => Key::KeyT,
        "KeyU" => Key::KeyU,
        "KeyV" => Key::KeyV,
        "KeyW" => Key::KeyW,
        "KeyX" => Key::KeyX,
        "KeyY" => Key::KeyY,
        "KeyZ" => Key::KeyZ,

        // Number row
        "Digit0" => Key::Num0,
        "Digit1" => Key::Num1,
        "Digit2" => Key::Num2,
        "Digit3" => Key::Num3,
        "Digit4" => Key::Num4,
        "Digit5" => Key::Num5,
        "Digit6" => Key::Num6,
        "Digit7" => Key::Num7,
        "Digit8" => Key::Num8,
        "Digit9" => Key::Num9,

        // Numpad
        "Numpad0" => Key::Kp0,
        "Numpad1" => Key::Kp1,
        "Numpad2" => Key::Kp2,
        "Numpad3" => Key::Kp3,
        "Numpad4" => Key::Kp4,
        "Numpad5" => Key::Kp5,
        "Numpad6" => Key::Kp6,
        "Numpad7" => Key::Kp7,
        "Numpad8" => Key::Kp8,
        "Numpad9" => Key::Kp9,
        "NumpadDecimal" => Key::KpDelete,
        "NumpadEnter" => Key::KpReturn,
        "NumpadAdd" => Key::KpPlus,
        "NumpadSubtract" => Key::KpMinus,
        "NumpadMultiply" => Key::KpMultiply,
        "NumpadDivide" => Key::KpDivide,

        // Modifiers
        "AltLeft" | "AltRight" => Key::Alt,
        "ControlLeft" => Key::ControlLeft,
        "ControlRight" => Key::ControlRight,
        "ShiftLeft" => Key::ShiftLeft,
        "ShiftRight" => Key::ShiftRight,
        "MetaLeft" => Key::MetaLeft,
        "MetaRight" => Key::MetaRight,
        "CapsLock" => Key::CapsLock,
        "NumLock" => Key::NumLock,

        // Navigation
        "ArrowUp" => Key::UpArrow,
        "ArrowDown" => Key::DownArrow,
        "ArrowLeft" => Key::LeftArrow,
        "ArrowRight" => Key::RightArrow,
        "Home" => Key::Home,
        "End" => Key::End,
        "PageUp" => Key::PageUp,
        "PageDown" => Key::PageDown,
        "Insert" => Key::Insert,
        "Delete" => Key::Delete,

        // Control keys
        "Enter" => Key::Return,
        "Escape" => Key::Escape,
        "Backspace" => Key::Backspace,
        "Tab" => Key::Tab,
        "Space" => Key::Space,
        "PrintScreen" => Key::PrintScreen,
        "ScrollLock" => Key::ScrollLock,
        "Pause" => Key::Pause,

        // Punctuation / symbols by physical key
        "Backquote" => Key::BackQuote,
        "Minus" => Key::Minus,
        "Equal" => Key::Equal,
        "BracketLeft" => Key::LeftBracket,
        "BracketRight" => Key::RightBracket,
        "Backslash" => Key::BackSlash,
        "IntlBackslash" => Key::IntlBackslash,
        "Semicolon" => Key::SemiColon,
        "Quote" => Key::Quote,
        "Comma" => Key::Comma,
        "Period" => Key::Dot,
        "Slash" => Key::Slash,

        // Function keys
        "F1" => Key::F1,
        "F2" => Key::F2,
        "F3" => Key::F3,
        "F4" => Key::F4,
        "F5" => Key::F5,
        "F6" => Key::F6,
        "F7" => Key::F7,
        "F8" => Key::F8,
        "F9" => Key::F9,
        "F10" => Key::F10,
        "F11" => Key::F11,
        "F12" => Key::F12,

        _ => return None,
    })
}

pub fn rdev_to_js_code(key: Key) -> Option<&'static str> {
    Some(match key {
        // Letters
        Key::KeyA => "KeyA",
        Key::KeyB => "KeyB",
        Key::KeyC => "KeyC",
        Key::KeyD => "KeyD",
        Key::KeyE => "KeyE",
        Key::KeyF => "KeyF",
        Key::KeyG => "KeyG",
        Key::KeyH => "KeyH",
        Key::KeyI => "KeyI",
        Key::KeyJ => "KeyJ",
        Key::KeyK => "KeyK",
        Key::KeyL => "KeyL",
        Key::KeyM => "KeyM",
        Key::KeyN => "KeyN",
        Key::KeyO => "KeyO",
        Key::KeyP => "KeyP",
        Key::KeyQ => "KeyQ",
        Key::KeyR => "KeyR",
        Key::KeyS => "KeyS",
        Key::KeyT => "KeyT",
        Key::KeyU => "KeyU",
        Key::KeyV => "KeyV",
        Key::KeyW => "KeyW",
        Key::KeyX => "KeyX",
        Key::KeyY => "KeyY",
        Key::KeyZ => "KeyZ",

        // Number row
        Key::Num0 => "Digit0",
        Key::Num1 => "Digit1",
        Key::Num2 => "Digit2",
        Key::Num3 => "Digit3",
        Key::Num4 => "Digit4",
        Key::Num5 => "Digit5",
        Key::Num6 => "Digit6",
        Key::Num7 => "Digit7",
        Key::Num8 => "Digit8",
        Key::Num9 => "Digit9",

        // Numpad
        Key::Kp0 => "Numpad0",
        Key::Kp1 => "Numpad1",
        Key::Kp2 => "Numpad2",
        Key::Kp3 => "Numpad3",
        Key::Kp4 => "Numpad4",
        Key::Kp5 => "Numpad5",
        Key::Kp6 => "Numpad6",
        Key::Kp7 => "Numpad7",
        Key::Kp8 => "Numpad8",
        Key::Kp9 => "Numpad9",
        Key::KpDelete => "NumpadDecimal",
        Key::KpReturn => "NumpadEnter",
        Key::KpPlus => "NumpadAdd",
        Key::KpMinus => "NumpadSubtract",
        Key::KpMultiply => "NumpadMultiply",
        Key::KpDivide => "NumpadDivide",

        // Modifiers
        Key::Alt => "AltLeft", // Note: JS has AltLeft/AltRight, rdev has single Alt
        Key::ControlLeft => "ControlLeft",
        Key::ControlRight => "ControlRight",
        Key::ShiftLeft => "ShiftLeft",
        Key::ShiftRight => "ShiftRight",
        Key::MetaLeft => "MetaLeft",
        Key::MetaRight => "MetaRight",
        Key::CapsLock => "CapsLock",
        Key::NumLock => "NumLock",

        // Navigation
        Key::UpArrow => "ArrowUp",
        Key::DownArrow => "ArrowDown",
        Key::LeftArrow => "ArrowLeft",
        Key::RightArrow => "ArrowRight",
        Key::Home => "Home",
        Key::End => "End",
        Key::PageUp => "PageUp",
        Key::PageDown => "PageDown",
        Key::Insert => "Insert",
        Key::Delete => "Delete",

        // Control keys
        Key::Return => "Enter",
        Key::Escape => "Escape",
        Key::Backspace => "Backspace",
        Key::Tab => "Tab",
        Key::Space => "Space",
        Key::PrintScreen => "PrintScreen",
        Key::ScrollLock => "ScrollLock",
        Key::Pause => "Pause",

        // Punctuation / symbols
        Key::BackQuote => "Backquote",
        Key::Minus => "Minus",
        Key::Equal => "Equal",
        Key::LeftBracket => "BracketLeft",
        Key::RightBracket => "BracketRight",
        Key::BackSlash => "Backslash",
        Key::IntlBackslash => "IntlBackslash",
        Key::SemiColon => "Semicolon",
        Key::Quote => "Quote",
        Key::Comma => "Comma",
        Key::Dot => "Period",
        Key::Slash => "Slash",

        // Function keys
        Key::F1 => "F1",
        Key::F2 => "F2",
        Key::F3 => "F3",
        Key::F4 => "F4",
        Key::F5 => "F5",
        Key::F6 => "F6",
        Key::F7 => "F7",
        Key::F8 => "F8",
        Key::F9 => "F9",
        Key::F10 => "F10",
        Key::F11 => "F11",
        Key::F12 => "F12",

        // Unsupported keys
        _ => return None,
    })
}

pub fn rdev_to_enigo_key(key: RdevKey) -> Option<EnigoKey> {
    Some(match key {
        // Letters
        RdevKey::KeyA => EnigoKey::A,
        RdevKey::KeyB => EnigoKey::B,
        RdevKey::KeyC => EnigoKey::C,
        RdevKey::KeyD => EnigoKey::D,
        RdevKey::KeyE => EnigoKey::E,
        RdevKey::KeyF => EnigoKey::F,
        RdevKey::KeyG => EnigoKey::G,
        RdevKey::KeyH => EnigoKey::H,
        RdevKey::KeyI => EnigoKey::I,
        RdevKey::KeyJ => EnigoKey::J,
        RdevKey::KeyK => EnigoKey::K,
        RdevKey::KeyL => EnigoKey::L,
        RdevKey::KeyM => EnigoKey::M,
        RdevKey::KeyN => EnigoKey::N,
        RdevKey::KeyO => EnigoKey::O,
        RdevKey::KeyP => EnigoKey::P,
        RdevKey::KeyQ => EnigoKey::Q,
        RdevKey::KeyR => EnigoKey::R,
        RdevKey::KeyS => EnigoKey::S,
        RdevKey::KeyT => EnigoKey::T,
        RdevKey::KeyU => EnigoKey::U,
        RdevKey::KeyV => EnigoKey::V,
        RdevKey::KeyW => EnigoKey::W,
        RdevKey::KeyX => EnigoKey::X,
        RdevKey::KeyY => EnigoKey::Y,
        RdevKey::KeyZ => EnigoKey::Z,

        // Number row
        RdevKey::Num0 => EnigoKey::Num0,
        RdevKey::Num1 => EnigoKey::Num1,
        RdevKey::Num2 => EnigoKey::Num2,
        RdevKey::Num3 => EnigoKey::Num3,
        RdevKey::Num4 => EnigoKey::Num4,
        RdevKey::Num5 => EnigoKey::Num5,
        RdevKey::Num6 => EnigoKey::Num6,
        RdevKey::Num7 => EnigoKey::Num7,
        RdevKey::Num8 => EnigoKey::Num8,
        RdevKey::Num9 => EnigoKey::Num9,

        // Numpad
        RdevKey::Kp0 => EnigoKey::Numpad0,
        RdevKey::Kp1 => EnigoKey::Numpad1,
        RdevKey::Kp2 => EnigoKey::Numpad2,
        RdevKey::Kp3 => EnigoKey::Numpad3,
        RdevKey::Kp4 => EnigoKey::Numpad4,
        RdevKey::Kp5 => EnigoKey::Numpad5,
        RdevKey::Kp6 => EnigoKey::Numpad6,
        RdevKey::Kp7 => EnigoKey::Numpad7,
        RdevKey::Kp8 => EnigoKey::Numpad8,
        RdevKey::Kp9 => EnigoKey::Numpad9,
        RdevKey::KpDelete => EnigoKey::Decimal,
        RdevKey::KpReturn => EnigoKey::Return,
        RdevKey::KpPlus => EnigoKey::Add,
        RdevKey::KpMinus => EnigoKey::Subtract,
        RdevKey::KpMultiply => EnigoKey::Multiply,
        RdevKey::KpDivide => EnigoKey::Divide,

        // Modifiers
        RdevKey::Alt => EnigoKey::Alt,
        RdevKey::ControlLeft => EnigoKey::Control,
        RdevKey::ControlRight => EnigoKey::Control,
        RdevKey::ShiftLeft => EnigoKey::Shift,
        RdevKey::ShiftRight => EnigoKey::Shift,
        RdevKey::MetaLeft => EnigoKey::Meta,
        RdevKey::MetaRight => EnigoKey::Meta,
        RdevKey::CapsLock => EnigoKey::CapsLock,
        RdevKey::NumLock => EnigoKey::Numlock,

        // Navigation
        RdevKey::UpArrow => EnigoKey::UpArrow,
        RdevKey::DownArrow => EnigoKey::DownArrow,
        RdevKey::LeftArrow => EnigoKey::LeftArrow,
        RdevKey::RightArrow => EnigoKey::RightArrow,
        RdevKey::Home => EnigoKey::Home,
        RdevKey::End => EnigoKey::End,
        RdevKey::PageUp => EnigoKey::PageUp,
        RdevKey::PageDown => EnigoKey::PageDown,
        RdevKey::Insert => EnigoKey::Insert,
        RdevKey::Delete => EnigoKey::Delete,

        // Control keys
        RdevKey::Return => EnigoKey::Return,
        RdevKey::Escape => EnigoKey::Escape,
        RdevKey::Backspace => EnigoKey::Backspace,
        RdevKey::Tab => EnigoKey::Tab,
        RdevKey::Space => EnigoKey::Space,
        RdevKey::PrintScreen => EnigoKey::PrintScr,
        RdevKey::ScrollLock => return None,
        RdevKey::Pause => EnigoKey::Pause,

        // Punctuation / symbols
        RdevKey::BackQuote     => EnigoKey::Unicode('`'),
        RdevKey::Minus         => EnigoKey::Unicode('-'),
        RdevKey::Equal         => EnigoKey::Unicode('='),
        RdevKey::LeftBracket   => EnigoKey::Unicode('['),
        RdevKey::RightBracket  => EnigoKey::Unicode(']'),
        RdevKey::BackSlash     => EnigoKey::Unicode('\\'),
        RdevKey::IntlBackslash => EnigoKey::Unicode('\\'), // best approximation
        RdevKey::SemiColon     => EnigoKey::Unicode(';'),
        RdevKey::Quote         => EnigoKey::Unicode('\''),
        RdevKey::Comma         => EnigoKey::Unicode(','),
        RdevKey::Dot           => EnigoKey::Unicode('.'),
        RdevKey::Slash         => EnigoKey::Unicode('/'),

        // Function keys
        RdevKey::F1 => EnigoKey::F1,
        RdevKey::F2 => EnigoKey::F2,
        RdevKey::F3 => EnigoKey::F3,
        RdevKey::F4 => EnigoKey::F4,
        RdevKey::F5 => EnigoKey::F5,
        RdevKey::F6 => EnigoKey::F6,
        RdevKey::F7 => EnigoKey::F7,
        RdevKey::F8 => EnigoKey::F8,
        RdevKey::F9 => EnigoKey::F9,
        RdevKey::F10 => EnigoKey::F10,
        RdevKey::F11 => EnigoKey::F11,
        RdevKey::F12 => EnigoKey::F12,

        // Unsupported keys
        _ => return None,
    })
}